/*
생일 3월 여자, 전화 NULL이면 출력 제외, 회원ID 오름차순
*/
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL and GENDER = 'W' and SUBSTRING(DATE_OF_BIRTH, 6, 7) = 03
ORDER BY MEMBER_ID