/*
각 INGREDIENT_TYPE에 대한 총 주문량 뽑기

*/
SELECT B.INGREDIENT_TYPE, sum(A.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY A.TOTAL_ORDER