/*
2022년 10월에 작성된거 잘 출력 정렬조건에 유의
*/
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
USING (BOARD_ID)
WHERE DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE, A.TITLE